### ISSUE TITLE
add documentation

### ISSUE THREAD

**Issue by mreinstein** [mreinstein/net-peer#7]
this library is a black box and unusable without usage docs

**Comment by owenmpierce** [comment]
This would be appreciated.  I've read all of gaffer's articles and I'd like to try playing with this library.

**Comment by mreinstein** [comment]
> I'd like to try playing with this library

@owenmpierce awesome! Would definitely appreciate any feedback. I'll put some time aside this afternoon to document the API and usage.

**Comment by mreinstein** [comment]
@owenmpierce I've got some basic API documentation in place, and an example showing how to use this library with node's UDP sockets. Would definitely welcome any feedback/ideas/etc. !

**Comment by owenmpierce** [comment]
Thank you for providing documentation.  I had reviewed index.js and it seemed pretty straight forward, but I wasn't sure what form my messages were supposed to be in.  It seems they need to be UInt8Arrays.

I do have a couple of questions:

1.  When I instantiate the SimplePeer, are there any special options I should pass in the [configuration object](https://github.com/feross/simple-peer#api).  In particular, the channelConfig property, which is used to configure the [https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/createDataChannel](DataChannel) that the SimplePeer uses, has the "ordered" and "maxRetransmits" properties, which I assume should be set to false and 0, respectively in order to emulate UDP.

2. With this library I can send and receive packets as UInt8Arrays, which means that I have to serialize my packet.  For me, this is fine.  Here's an outline of how I'm creating packets:


- I have MeasureStream, WriteStream, and ReadStream classes that are based on those found in Gaffer's "protocol2.h" header file.  
- My packet classes all include a .serialize(stream) method.  
- To read a packet, a ReadStream is instantiated with a buffer, and then packet.serialize(readStream) deserializes the buffer so that the packet can be used by my application.  
- Likewise, to write a packet, I create my packet, create a MeasureStream, and call packet.serialize(measureStream) in order to get the size of the write buffer.  WriteStream is instantiated with a buffer of this size and packet.serialize(writeStream) is called, and then writeStream.buffer is sent using the transport layer.
- Right now I'm just packing integers as either Uint8, Uint16, or Uint32s, depending on what the maximum and minimum values they take are because it's simpler than making a bitpacker.

Anyway, I'm wondering if you plan on adding some kind of packet registration system and packet description language to net-peer so that sendReliable(), sendUnreliable(), and the subscribe() handler can operate with actual javascript objects (i.e. Packets) instead of arrays.   Or, do you think that anyone who uses the library should figure out his own packet serialization strategy?

**Comment by mreinstein** [comment]
> are there any special options I should pass in

Yes, exactly. You want to shut off some default webRTC behaviors. here's what I have for my config:

```javascript
channelConfig: { reliable: false, maxRetransmits: 0, ordered: false }
```

I would like to eventually add an example based on `simple-peer` in the `examples/` folder to show how this would work end-to-end.


>  I'm wondering if you plan on adding some kind of packet registration system and packet 
> description language to net-peer so that sendReliable(), sendUnreliable(), and the subscribe() 
> handler can operate with actual javascript objects (i.e. Packets) instead of arrays. Or, do you 
> think that anyone who uses the library should figure out his own packet serialization strategy?

Hmm, that's a good question! I know one of the strength's of Gaffer's system is it automatically handles serialize/deserialize, somewhat magically. Right now I have some custom classes that I use in my game which provide pack/unpack functionality. Would be open to discussion on this, either as an API change, or as another module that would work with `net-peer` to provide this layer.

**Comment by mreinstein** [comment]
@owenmpierce still very open to feedback on this

**Comment by owenmpierce** [comment]
Oh, sorry. 

Yes, now that I think about it, separating the serialization layer and the transport layer in to two different libraries as you suggest would be a better idea.  There's a clear separation of concerns between these two layers, and a user wouldn't be forced to include the serialization functionality if he already has some existing code to do this.  Such a net-packet object would emit and accept UInt8Arrays to and from the net-peer object.

A couple more points:
1.  I'm wondering if net-peer could publish 'ping' events in addition to 'data' events.  The reason being that some people (like me) might like to have more rapid feedback than an exponential moving average with an alpha of 0.9, as well as keeping a record of high-water-mark latency over the last x seconds.  The ping event handler function would accept as an argument a ping message, which would simply be an object with a time delta and a sequence number (maybe an absolute send time).  Additionally, some way to adjust the frequency of pings could be useful.

2. Do you think that support for multiple independently sequenced channels would be a useful (or possible) addition?  Enet does this, although I think each channel needs to be designated as reliable or unreliable.  I don't see myself needing this, but I could see the appeal of hooking up different callbacks to different channels. 

Finally, I'd like to know if "chunk" messages  will arrive in order with other reliable messages.  If I send a reliable message, a chunk, and then another reliable message, is the chunk guaranteed to arrive between the two reliable messages on the other end?  I looked at the source and it seems like if I just send a chunk and then a reliable message, then the reliable message would always arrive behind the chunk because the reliable message wouldn't be sent while the chunk packets were in flight.  But will a chunk start while there are reliable messages waiting to be acked?

**Comment by mreinstein** [comment]
@owenmpierce sorry for the high reply latency! I'm at the end of the long day so if any of these responses don't make sense or I've missed something please let me know.

> some people (like me) might like to have more rapid feedback than an exponential 
> moving average with an alpha of 0.9

The unreliable transport actually calculates latency at a very high resolution already. Unreliable transport doesn't resend failed packets, but each received packet *is* acked, and that ack has a timestamp that is used to measure latency.  Assuming the bulk of your networking bandwidth is going to unreliable packets (character positions, rotations, projectile data, other ephemeral immediate data, which tends to be the lion's share of bandwidth consumption) you're going to get a lot of latency info, which in turn will give you a very high resolution measure.

> as well as keeping a record of high-water-mark latency over the last x seconds.

We could add high water mark quite easily to the unreliable transport system. I could expose a `getHighwaterMark()` and `resetHighwaterMark()` to accomplish this perhaps?


> Do you think that support for multiple independently sequenced channels would 
> be a useful (or possible) addition?

I'm not sure I understand what you mean by `independently sequenced channels`. Can you elaborate on this a bit?


> I'd like to know if "chunk" messages will arrive in order with other reliable messages.

Except for reliable messages, there's no guarantee that different messages will arrive in the order that you send them, because the underlying networking layer is unreliable, and packets may be received out of order or dropped, if that makes sense. Your simulation/game has to handle the asynchronous nature of message arrival.

Something else to keep in mind; When you're sending/receiving a chunk (e.g., loading a level), you really don't want a lot of other stuff going over the connection. chunk transport saturates the network connection to maximize throughput/transfer speed. That is going to be at odds with the goals of the reliable & unreliable transport layers I think. (i.e., you shouldnt be sending receiving a lot of time sensitive game data while slamming the connection with a level load.)

I'm not sure if I addressed everything, happy to discuss further. Thanks for the additional thoughts!

**Comment by owenmpierce** [comment]
I see.  Yes, a getHighWaterMark function would be good, then.

By independently sequenced channels, I simply mean different channels where reliable messages sent over one channel will not stall reliable messages sent over the other.  So, I could have a "chat" channel and a "game" channel, and reliable messages sent on the chat channel won't stall those sent on the channel for game.  Maybe it's not necessary though.

**Comment by mreinstein** [comment]
@owenmpierce 

> Yes, a getHighWaterMark function would be good, then.

created #9 to for this. Feel free to submit a PR if you're feeling up to it! 👍  If you don't have time I'll work on this though.

> By independently sequenced channels, I simply mean different channels where 
> reliable messages sent over one channel will not stall reliable messages sent over the other.

Ahh, I see what you mean. Thanks for the clarification. The only way messages might block the arrival of other messages is if you experienced very heavy packet loss, over an extended period of time (e.g., dropping 90% of packets for a large chunk of time.) In that case you'd end up with a lot of queued up messages waiting to be sent. 

In most cases, this heavy packet loss would be due to degraded network connection quality. Adding other independent channels wouldn't alleviate this. Assuming you don't have crazy packet loss and you're not overloading the connection with more data than it can transport this message stalling shouldn't happen.
